//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UserDetail
    {
        public int id { get; set; }
        [Required]
        public string username { get; set; }
        [Required]
        public string firstname { get; set; }
        [Required]
        public string middlename { get; set; }
        [Required]
        public string lastname { get; set; }
        [Required]
        [DataType(DataType.EmailAddress,ErrorMessage = "The email address is not valid")]
        public string email { get; set; }
        public Nullable<int> mobileNo { get; set; }
        [Required]
        public string password { get; set; }
        
        [NotMapped]
        [Required]
        [Compare("password",ErrorMessage ="Confirm password doesn't match")]
        public string repassword { get; set; }

    }
}
